[package]
name = "html-bindgen"
description = "Tool to convert HTML WebIDL files to a structured representation"
license = "Apache-2.0 OR MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
weedle = "0.12.0"
convert_case = "0.6.0"
indoc = "2.0.0"
